/* Shared LCD geometry constants. */
#ifndef FX_EMU_CORE_LCD_GEOMETRY_H
#define FX_EMU_CORE_LCD_GEOMETRY_H

#define FX_EMU_LCD_VISIBLE_WIDTH 96
#define FX_EMU_LCD_VISIBLE_HEIGHT 32
#define FX_EMU_LCD_PAGE_HEIGHT 8
#define FX_EMU_LCD_PAGE_COUNT (FX_EMU_LCD_VISIBLE_HEIGHT / FX_EMU_LCD_PAGE_HEIGHT)
#define FX_EMU_LCD_FRAMEBUFFER_SIZE (FX_EMU_LCD_VISIBLE_WIDTH * FX_EMU_LCD_PAGE_COUNT)

#endif /* FX_EMU_CORE_LCD_GEOMETRY_H */


