name: MSBuild

on:
  # pull_request:
    # branches: [ "stable" ]
  # push:
    # branches: [ "stable" ]
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  CASIOEMU_ONLINE_BUILD_KEY_ID: ${{ secrets.CASIOEMU_ONLINE_BUILD_KEY_ID }}
  CASIOEMU_ONLINE_BUILD_KEY_B64: ${{ secrets.CASIOEMU_ONLINE_BUILD_KEY_B64 }}
  CASIOEMU_ONLINE_SERVER_KEY_ID: ${{ secrets.CASIOEMU_ONLINE_SERVER_KEY_ID }}
  CASIOEMU_ONLINE_SERVER_PUBLIC_KEY_B64: ${{ secrets.CASIOEMU_ONLINE_SERVER_PUBLIC_KEY_B64 }}

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7

    - name: Configure and build x64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cmake -S . -B build-x64 -A x64 -DBUILD_EXECUTABLE=ON
        cmake --build build-x64 --config ${{env.BUILD_CONFIGURATION}} --parallel

    - name: Configure and build x86
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cmake -S . -B build-x86 -A Win32 -DBUILD_EXECUTABLE=ON
        cmake --build build-x86 --config ${{env.BUILD_CONFIGURATION}} --parallel

    - name: Upload x86 Build Artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: Release-x86
        path: build-x86\CasioEmuMsvc\${{env.BUILD_CONFIGURATION}}
        if-no-files-found: error

    - name: Upload x64 Build Artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: Release-x64
        path: build-x64\CasioEmuMsvc\${{env.BUILD_CONFIGURATION}}
        if-no-files-found: error
