name: PR Build Check

on:
  pull_request:
    branches: [ "stable" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-latest
    name: Windows (x64)

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x64 ${{env.SOLUTION_FILE_PATH}}

  build-linux:
    runs-on: ubuntu-latest
    name: Linux (x64)

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build
      run: |
        chmod +x build-linux.sh
        sudo DEBIAN_FRONTEND=noninteractive ./build-linux.sh -y
